config/routes.rb
Rails.application.routes.draw do
  get 'site/index'
  get 'site/login'
  get 'site/talents'
  root 'site#index'
  resources :competitions do
  	resources :registrations do
      resources :homologations, only: [:create]
    end
    resources :participations do
      resources :checkin, only: [:create]
    end
    resources :homologations, only: [:index]
    resources :checkin, only: [:index]
    resources :certificates, only: [:index]
  end
  resources :institutions
  devise_for :admins
  devise_for :delegates
  devise_for :competitors
end

app/models/competition.rb
class Competition < ApplicationRecord
  validates :edition, presence: true
  validates :duration, presence: true
  has_many :registrations
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:edition, :level, :date, :duration, :registration_start, :registration_end)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_with(model: competition, local: true) do |form| %>
  <% if competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :edition %>
    <%= form.text_field :edition %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.select :level, options_for_select([
                ["Médio", "M"],
                ["Superior", "S"]
              ], "email") %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :registration_start %>
    <%= form.datetime_select :registration_start %>
  </div>

  <div class="field">
    <%= form.label :registration_end %>
    <%= form.datetime_select :registration_end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<div class="container" style="padding-top: 64px">
<h1>Editing Competition</h1>

<%= render 'form', competition: @competition %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>
</div>

app/views/competitions/index.html.erb
<div class="container" style="padding-top: 64px">
<p id="notice"><%= notice %></p>

<h1>Competitions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Edition</th>
      <th>Level</th>
      <th>Date</th>
      <th>Duration</th>
      <th>Registration start</th>
      <th>Registration end</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.edition %></td>
        <td><%= competition.level %></td>
        <td><%= competition.date %></td>
        <td><%= competition.duration %></td>
        <td><%= competition.registration_start %></td>
        <td><%= competition.registration_end %></td>
        <td><%= link_to 'Show', competition %></td>
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Homologar Times', competition_homologations_path(competition) %></td>
        <td><%= link_to 'Checkin', competition_checkin_index_path(competition) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition', new_competition_path %>
</div>

app/views/competitions/new.html.erb
<div class="container" style="padding-top: 64px">
<h1>New Competition</h1>

<%= render 'form', competition: @competition %>

<%= link_to 'Back', competitions_path %>
</div>

app/views/competitions/show.html.erb
<div class="container" style="padding-top: 64px">
<p id="notice"><%= notice %></p>

<p>
  <strong>Edition:</strong>
  <%= @competition.edition %>
</p>

<p>
  <strong>Level:</strong>
  <%= @competition.level %>
</p>

<p>
  <strong>Date:</strong>
  <%= @competition.date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @competition.duration %>
</p>

<p>
  <strong>Registration start:</strong>
  <%= @competition.registration_start %>
</p>

<p>
  <strong>Registration end:</strong>
  <%= @competition.registration_end %>
</p>

<%= link_to 'Edit', edit_competition_path(@competition) %> |
<%= link_to 'Back', competitions_path %>
</div>