config/routes.rb
Rails.application.routes.draw do
  get 'site/index'
  get 'site/login'
  get 'site/talents'
  root 'site#index'
  resources :competitions do
  	resources :registrations do
      resources :homologations, only: [:create]
    end
    resources :participations do
      resources :checkin, only: [:create]
    end
    resources :homologations, only: [:index]
    resources :checkin, only: [:index]
    resources :certificates, only: [:index]
  end
  resources :institutions
  devise_for :admins
  devise_for :delegates
  devise_for :competitors
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
class Competition < ApplicationRecord
  validates :edition, presence: true
  validates :duration, presence: true
  has_many :registrations
end

app/models/competitor.rb
class Competitor < ApplicationRecord
  belongs_to :institution
  has_many :participations
  has_many :contacts
  # validates :institution_id, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :tipo, presence: true
  validates :value, presence: true
  belongs_to :competitor
end

app/models/delegate.rb
class Delegate < ApplicationRecord
  belongs_to :institution
  # validates :institution_id, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/institution.rb
class Institution < ApplicationRecord
	validates :name, presence: true
	validates :city, presence: true
	validates :state, presence: true
    has_many :competitors
    has_many :delegates
end

app/models/participation.rb
class Participation < ApplicationRecord
	belongs_to :competitor
	belongs_to :registration
end

app/models/registration.rb
class Registration < ApplicationRecord
  validates :time, presence: true
  belongs_to :competition
  belongs_to :delegate
  has_many :participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_update_params, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :publico, :matricula, :institution_id, contacts_attributes: [:id, :tipo, :value, :_destroy]])
  end

   def configure_permitted_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :publico, :matricula, :institution_id, contacts_attributes: [:id, :tipo, :value, :_destroy]])
   end
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :authenticate_competitor!
  def index

  	
  	@current_competitor = current_competitor
  	@competition = Competition.find(params[:competition_id])
  	render :layout => false
  end
end

app/controllers/checkin_controller.rb
class CheckinController < ApplicationController
  before_action :authenticate_admin!
  def index
  	@competition = Competition.find(params[:competition_id])
  end

  def create
  	competition = Competition.find(params[:competition_id])
  	participation = Participation.find(params[:participation_id])
  	if participation.presenca.nil?
  		participation.presenca = params[:status]
  		participation.save
  	end
  	redirect_to competition_checkin_index_path(competition)
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:edition, :level, :date, :duration, :registration_start, :registration_end)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	@competitions = Competition.all
  end

  def login
  end

  def talents
  	@competitors = Competitor.where(publico:1).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/checkin_helper.rb
module CheckinHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/homologations_helper.rb
module HomologationsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/certificates/index.html.erb
<style>
body {
	background-image: url('https://png.pngtree.com/thumb_back/fw800/back_pic/04/47/51/665858c95c31b60.jpg');
	    background-repeat: no-repeat, repeat;
}
</style>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= current_competitor.name %></h1>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Participou da <%= @competition.edition %>ª edição do POP</p> 

app/views/checkin/index.html.erb
<div class="container" style="padding-top: 64px">
<h1></h1>

<h1>Checkin - POP - <%= @competition.edition %>ª Edição - <%= @competition.level %></h1>

<table class="table">
	<tr>
		<td>Nome</td>
		<td>Status</td>
	</tr>
<% @competition.registrations.each do |r| %>

	<% r.participations.each do |p| %>
		
		<tr>
			<td><%= p.competitor.name %></td>
				<td>
					<% if p.presenca.nil? %>
					<%= link_to 'Marcar presença', competition_participation_checkin_index_path(@competition, p, status: 'd'),  method: :post  %>
						<% else %>
						Presente
						<% end %>
					</td>
		</tr>
		
	<% end %>
<% end %>
</table>
</div>

app/views/site/_competitor.html.erb
<div class="container" style="padding-top: 64px" >

<h2>Minhas competições</h2>
	<table class="table">
		<tr>
			<th>
				Edição
			</th>
			<th>Time</th>
			<th></th>
		</tr>

		<% current_competitor.participations.each do |p| %>
			<tr>
				<td><%= p.registration.competition.edition %></td>
				<td><%= p.registration.time %></td>
				<td>
					<% if !p.presenca.nil? %>
						<%= link_to 'Emitir certificado', competition_certificates_path(p.registration.competition.id) %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/site/_delegate.html.erb
<div class="container" style="padding-top: 64px" align="center">
<h2>Competições</h2>
	<table class="table">
		  <thead>
		<tr>
			<th>
				Edição
			</th>
			<th>
				Nível
			</th>
			<th>
				Inicio das incrições
			</th>
			<th>
				Fim das incrições
			</th>
		</tr>
		 </thead>

		<% @competitions.each do |competition| %>
			<tr>
				<td><%= competition.edition %></td>
				<td><%= competition.level %></td>
				<td><%= competition.registration_start %></td>
				<td><%= competition.registration_end %></td>
				<td><%= link_to 'Inscrições', competition_registrations_path(competition.id) %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/site/index.html.erb
<% if admin_signed_in? %>
	<%= render partial: 'admin' %>
<% elsif competitor_signed_in? %>
	<%= render partial: 'competitor' %>
<% elsif delegate_signed_in? %>
	<%= render partial: 'delegate' %>
<% else %>
	<div class="jumbotron" align="center">
	  <h1 class="display-4">PROJETO OLÍMPICO DE PROGRAMAÇÃO</h1>
	  <p class="lead">Programar é uma arte e competir é muito divertido!</p>
	</div>
<% end %>

app/views/site/login.html.erb
<div class="container" style="padding-top: 64px" align="center">


		<h2>Entrar</h2>
		<h3>Para entrar escolha qual o seu perfil!</h3>
  <div class="row">
    <div class="col">
    	
 	<%= link_to image_tag("http://4.bp.blogspot.com/_qXAVYQgQzzk/SQu1mR4tiGI/AAAAAAAAARI/jNuRfWMH2Kk/s400/nerd+no+PC+4.jpg", :class => 'rounded-circle', width: 150, height: 150), new_competitor_session_path %>
 	<h4>Competidor</h4>
    </div>
    <div class="col">
    	
     <%= link_to image_tag("https://ssl8972.websiteseguro.com/curtiram/images/fotos/mh_interna_melhores-filmes-chuck-norris%20(17).jpg", :class => 'rounded-circle', width: 150, height: 150), new_delegate_session_path %>    
     <h4>Delegado</h4>
    </div>
  </div>

</div>

app/views/site/talents.html.erb
<div class="album py-5 bg-light">
        <div class="container">
        	<h2 align="center">Banco de talentos</h2>

          <div class="row">
          	<% @competitors.each do |competitor| %>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164afbdb726%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164afbdb726%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.7265625%22%20y%3D%22120.3%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                <div class="card-body">
                  <p class="card-text"><%= competitor.name %>, </p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">Entrar em contato</button>
                    </div>
                    <small class="text-muted"><%= competitor.institution.name %></small>
                  </div>
                </div>
              </div>
            </div>
<p></p>
<% end %>


          </div>
        </div>
      </div>