config/routes.rb
Rails.application.routes.draw do
  get 'site/index'
  get 'site/login'
  get 'site/talents'
  root 'site#index'
  resources :competitions do
  	resources :registrations do
      resources :homologations, only: [:create]
    end
    resources :participations do
      resources :checkin, only: [:create]
    end
    resources :homologations, only: [:index]
    resources :checkin, only: [:index]
    resources :certificates, only: [:index]
  end
  resources :institutions
  devise_for :admins
  devise_for :delegates
  devise_for :competitors
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
class Competition < ApplicationRecord
  validates :edition, presence: true
  validates :duration, presence: true
  has_many :registrations
end

app/models/competitor.rb
class Competitor < ApplicationRecord
  belongs_to :institution
  has_many :participations
  has_many :contacts
  # validates :institution_id, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :tipo, presence: true
  validates :value, presence: true
  belongs_to :competitor
end

app/models/delegate.rb
class Delegate < ApplicationRecord
  belongs_to :institution
  # validates :institution_id, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/institution.rb
class Institution < ApplicationRecord
	validates :name, presence: true
	validates :city, presence: true
	validates :state, presence: true
    has_many :competitors
    has_many :delegates
end

app/models/participation.rb
class Participation < ApplicationRecord
	belongs_to :competitor
	belongs_to :registration
end

app/models/registration.rb
class Registration < ApplicationRecord
  validates :time, presence: true
  belongs_to :competition
  belongs_to :delegate
  has_many :participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_update_params, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :publico, :matricula, :institution_id, contacts_attributes: [:id, :tipo, :value, :_destroy]])
  end

   def configure_permitted_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :publico, :matricula, :institution_id, contacts_attributes: [:id, :tipo, :value, :_destroy]])
   end
end

app/controllers/checkin_controller.rb
class CheckinController < ApplicationController
  before_action :authenticate_admin!
  def index
  	@competition = Competition.find(params[:competition_id])
  end

  def create
  	competition = Competition.find(params[:competition_id])
  	participation = Participation.find(params[:participation_id])
  	if participation.presenca.nil?
  		participation.presenca = params[:status]
  		participation.save
  	end
  	redirect_to competition_checkin_index_path(competition)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	@competitions = Competition.all
  end

  def login
  end

  def talents
  	@competitors = Competitor.where(publico:1).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/checkin_helper.rb
module CheckinHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/homologations_helper.rb
module HomologationsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #00BFA5;">
  <a class="navbar-brand" href="/">Maratona POP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
   <li class="nav-item">
        <%= link_to 'Banco de talentos', site_talents_path, class: "nav-link" %>
      </li>

      <% if admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "Competição", competitions_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Intituição", institutions_path, class: "nav-link" %>
        </li>
      <% elsif competitor_signed_in? %>
      <% elsif delegate_signed_in? %>
       <% else %>
        <li class="nav-item">
            <%= link_to 'Entrar', site_login_path, class: "nav-link" %>
        </li>
      <% end %>



    </ul>

    <div class="navbar-text pull-right">

            <% if admin_signed_in? %>
            Olá <strong>Admin</strong>.
             <%= link_to 'Atualizar perfil', edit_admin_registration_path, :class => 'navbar-link' %> |
        <%= link_to 'Sair', destroy_admin_session_path, method: 'delete', class: 'navbar-link' %>
      <% elsif competitor_signed_in? %>
      Olá <strong><%= current_competitor.name %></strong>.
       <%= link_to 'Atualizar perfil', edit_competitor_registration_path, :class => 'navbar-link' %> |
     <%= link_to 'Sair', destroy_competitor_session_path, method: 'delete', class: 'navbar-link' %>
      <% elsif delegate_signed_in? %>
      Olá <strong><%= current_delegate.name %></strong>.
       <%= link_to 'Atualizar perfil', edit_delegate_registration_path, :class => 'navbar-link' %>|
      <%= link_to 'Sair', destroy_delegate_session_path, method: 'delete', class: 'navbar-link' %>
     
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/menu' %>
    <%= yield %>
  </body>
</html>